<?php
/**
 * @file
 * Ding context-related search module.
 */

/**
 * Implements hook_menu().
 */
function ding_context_search_menu() {
  $items['admin/config/ding/dcrs'] = array(
    'title' => 'Ding context-related search settings',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access administration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_context_search_admin_settings'),
    'file' => 'ding_context_search.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ding_context_search_theme($existing, $type, $theme, $path) {
  return array(
    'ding_context_search_table' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Custom theme handler for rendering prices as table.
 */
function theme_ding_context_search_table($variables) {
  $form = $variables['form'];
  $rows = array();
  foreach (element_children($form['filters']) as $id) {
    $rows[] = array(
      'url' => drupal_render($form['filters'][$id]['url']),
      'filter' => drupal_render($form['filters'][$id]['filter']),
      'remove' => drupal_render($form['filters'][$id]['remove']),
    );
  }

  $header = array(
    t('URL'),
    t('Filter'),
    t('Remove'),
  );

  $output = theme('table', array(
    'rows' => $rows,
    'header' => $header,
    'empty' => t('Click to add more for adding a row.'),
  ));
  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ding_context_search_form_search_block_form_alter(&$form, &$form_state) {
  $form['#submit'][] =  'ding_context_search_filter_submit';
//  $form['actions']['submit']['#submit'][] =  'ding_context_search_filter_submit';
}

/**
 * Submit handler for adding context related filters.
 *
 * @param $form
 * @param $form_state
 */
function ding_context_search_filter_submit($form, &$form_state) {
  $url = parse_url($_SERVER['HTTP_REFERER']);
//  var_dump($url);
}
